### ISSUE TITLE
nur die ersten 3 Einträge erzeigen Objekte

### ISSUE THREAD

**Issue by redseasix** [simatec/ioBroker.pegelalarm#127]
Meine Testumgebung:

Plattform: linux arm64
RAM: 7.6 GB
Node.js: v19.3.0(19.7.0)
NPM: 9.2.0

Pegelalarm: 
Installierte Instanzen:1
Verfügbare Version:1.2.8
Installierte Version:1.2.8

Egal welche Pegelstände ich mir raussuche, es werden immer nur die ersten 3 Messstellen mit Pegelwerten via. Crom befüllt und als Objekt abgelegt. leider nichts für die Messtelle 4 und 5.

**Comment by simatec** [comment]
Der Fehler ist nicht nachvollziehbar ...
Bitte prüfe deine Einstellungen
