### ISSUE TITLE
Level Worms (Rhein) is ignored

### ISSUE THREAD

**Issue by Erbse69** [simatec/ioBroker.pegelalarm#86]
When using Mainz (Rhein) the adapter creates an object pegelalarm.0.stations.mainz and fetches the values. 
When switching to Worms (or creating a second entry for Worms) this is ignored totally, the adapter does not create the folder for Worms and does not fetch any values. Maybe there's an issue with this special station.
When leaving the station name empty, the adapter creates object folders for many stations along the Rhein, but Worms is missing.

Pegelalarm v1.2.7, running on Admin V6.0.3 (but I saw the same behavior with older versions also), node: v14.18.2, js-controller: 4.0.23

There's no error shown in the log file.

If you need any more information please let me know.

Best regards,
Erbse

**Comment by simatec** [comment]
This is a API Problem... Please read a Issue on API
