### ISSUE TITLE
Ist das richtig das Frankfurt am Main in Hessen fehlt

### ISSUE THREAD

**Issue by Damrak2022** [simatec/ioBroker.pegelalarm#93]
Ich habe 4 Stationen hinzugefügt
Frankfurt am Main - Main - Osthafen
Rhein - Bingen
Trave - Lübeck Moisling
Trave - Travemünde

Unter den Objekten wird mir aber nur die Station Travemünde angezeigt. Alle anderen fehlen.
Hier ein Auszug aus dem Debug Log

2022-08-15 13:57:25.391 | debug | Poll all states
-- | -- | --
host.homebridge | 2022-08-15 13:57:21.711 | info | instance system.adapter.pegelalarm.0 terminated with code 0 (NO_ERROR)
pegelalarm.0 | 2022-08-15 13:57:21.052 | info | Terminated (NO_ERROR): Without reason
pegelalarm.0 | 2022-08-15 13:57:21.051 | debug | Plugin sentry destroyed
pegelalarm.0 | 2022-08-15 13:57:21.040 | debug | cleaned everything up...
pegelalarm.0 | 2022-08-15 13:57:20.847 | debug | Check for deleting old states is started
pegelalarm.0 | 2022-08-15 13:57:20.846 | debug | Pegelalarm Request is completed
pegelalarm.0 | 2022-08-15 13:57:19.844 | debug | Pegelalarm request for measuring station 4 is finish ...
pegelalarm.0 | 2022-08-15 13:57:19.844 | debug | Pegelalarm request done
host.homebridge | 2022-08-15 13:57:17.991 | error | instance system.adapter.pegelalarm.0 terminated with code 7 (ADAPTER_ALREADY_RUNNING)
pegelalarm.0 | 2022-08-15 13:57:17.591 | debug | Pegelalarm API is available ... Status: 200
pegelalarm.0 | 2022-08-15 13:57:17.488 | debug | https://api.pegelalarm.at/api/station/1.0/list?countryCode=DE&qRegion=Trave&qWater=Trave&qStationName=Travem%C3%BCnde
pegelalarm.0 | 2022-08-15 13:57:17.487 | debug | Pegelalarm request for measuring station 4 is started ...
pegelalarm.0 | 2022-08-15 13:57:17.383 | warn | Terminated (ADAPTER_ALREADY_RUNNING): Without reason
pegelalarm.0 | 2022-08-15 13:57:17.382 | debug | Plugin sentry destroyed
pegelalarm.0 | 2022-08-15 13:57:17.380 | error | pegelalarm.0 already running
pegelalarm.0 | 2022-08-15 13:57:17.371 | debug | States connected to redis: 127.0.0.1:9000
pegelalarm.0 | 2022-08-15 13:57:17.314 | debug | States create User PubSub Client
pegelalarm.0 | 2022-08-15 13:57:17.311 | debug | States create System PubSub Client
pegelalarm.0 | 2022-08-15 13:57:17.249 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
pegelalarm.0 | 2022-08-15 13:57:17.187 | debug | Objects connected to redis: 127.0.0.1:9001
pegelalarm.0 | 2022-08-15 13:57:17.178 | debug | Objects client initialize lua scripts

**Comment by simatec** [comment]
Auf die API habe ich leider keine Einfluss ... Hier müsste dort ein Issue aufgemacht werden
